### ISSUE TITLE
Question #231 cannot be compiled

### ISSUE THREAD

**Issue by wonderfulzzd** [knatten/cppquiz#148]
Question #231 cannot be compiled. The compiler reported:

test.cc:10:34: error: two or more data types in declaration of ‘type name’
     virtual auto f() -> override override{
                                  ^~~~~~~~
test.cc: In function ‘int main()’:
test.cc:17:13: error: invalid cast to abstract class type ‘Derived’
     Derived().f();
             ^
test.cc:9:8: note:   because the following virtual functions are pure within ‘Derived’:
 struct Derived : Base {
        ^~~~~~~
test.cc:6:22: note: 	virtual override Base::f()
     virtual override f() = 0;

**Comment by knatten** [comment]
Which compiler are you using? This compiles on msvc 19.20 and clang 8.0.0. It seems to fail on gcc 8.3. I think this is a bug in gcc.

**Comment by knatten** [comment]
Closing due to lack of activity.
